### ISSUE TITLE
Support for DNG V1.7 

### ISSUE THREAD

**Issue by BR1py** [ncruces/dcraw#9]
Can you please add support for DNG format version 1.7 (JXL compressed files)?
Those files are much smaller compared with old DNG files (especially if lossy compression is used).

**Comment by BR1py** [comment]
Sorry saw that this is just a mirror

**Comment by gitoss** [comment]
> Sorry saw that this is just a mirror

I hope you'll reach the author of dcraw - I only found out about the lacking compatibilty with newer dng by trial & error, because the docs don't mention it.

The last dng format that seems to be compatible with current dcraw is 1.1 (check -IFD0:DNGBackwardVersion with exiftool). However, you might be able to downgrade the newer dng version your camera outputs by setting Adobe DNG Converter to ACR 12.4. 

For me, Adobe DNG Converter is able to convert back and forward classic JPEG thumbnails & newer JPEG-XL.

**Comment by ncruces** [comment]
I have never been able to contact the original author.

Tbh, my only use for `dcraw` is extracting thumbnails of raw files, so I'm unlikely to pursue this.
